#!/usr/bin/env bash
# Configure domain zone so subdomain points to load-balancer IP

display_info() {
    local subdomain=$1
    local domain=$2

    local answer=$(dig +short "$subdomain.$domain")

    if [[ -n "$answer" ]]; then
        local record_type=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/{getline;print $3}')
        echo "The subdomain $subdomain is a $record_type record and points to $answer"
    fi
}

domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for subdomain in "${subdomains[@]}"; do
    display_info "$subdomain" "$domain"
done
