#!/usr/bin/env bash
# Configure domain zone so subdomain points to load-balancer IP

func () 
{
    local subdomain=$1
    local domain=$2

    local answer=$(dig +short "$subdomain.$domain")

    if [[ -n "$answer" ]]; then
        local record_type=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/{getline;print $3}')
        echo "The subdomain $subdomain is a $record_type record and points to $answer"
    fi
}

domain=$1

func "www" "$domain"
func "lb-01" "$domain"
func "web-01" "$domain"
func "web-02" "$domain"
