#!/usr/bin/env bash
# Install nginx web server

# Install nginx
apt-get update
apt-get install -y nginx

# Create dir and file
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html

# Configure nginx
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default

# restart nginx
service nginx restart
