#!/usr/bin/env bash
# Install nginx web server

# Install nginx
apt-get update
apt-get install -y nginx

# Directory and file
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Configure nginx
printf %s "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root   /etc/nginx/html;
  index  index.html index.htm;
  }" >  /etc/nginx/site-available/default

# Restart nginx
service nginx restart
