#!/bin/env bash
# Process and PID file

pid_file="var/run/myscript.pid"

function finish {
  echo "Y U no love me?!"
  exit 0
}

function terminate {
  echo "I hate the kill command"
  exit 0
}

function remove {
  rm $pid_file
  exit 0
}

echo $$ > $pid_file

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'terminate && remove' SIGTERM
  trap 'finish' SIGINT
  trap 'remove' SIGQUIT
done
