#!/usr/bin/env bash

# Set the user that nginx will run as
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change the prot that nginx listens on
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Set the permission
chmod 644 /etc/nginx/nginx.conf

# Stop apache
pkill apache2

# Restart
sudo service nginx start
